<a href="https://colab.research.google.com/github/muraliRoyal1/venkatasiva_INFO5731_Fall2020/blob/master/In_class_exercise_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The fifth In-class-exercise (9/30/2020, 20 points in total)

In exercise-03, I asked you to collected 500 textual data based on your own information needs (If you didn't collect the textual data, you should recollect for this exercise). Now we need to think about how to represent the textual data for text classification. In this exercise, you are required to select 10 types of features (10 types of features but absolutely more than 10 features) in the followings feature list, then represent the 500 texts with these features. The output should be in the following format:
![image.png](attachment:image.png)

The feature list:

* (1) tf-idf features
* (2) POS-tag features: number of adjective, adverb, auxiliary, punctuation, complementizer, coordinating conjunction, subordinating conjunction, determiner, interjection, noun, possessor, preposition, pronoun, quantifier, verb, and other. (select some of them if you use pos-tag features)
* (3) Linguistic features:
  * number of right-branching nodes across all constituent types
  * number of right-branching nodes for NPs only
  * number of left-branching nodes across all constituent types
  * number of left-branching nodes for NPs only
  * number of premodifiers across all constituent types
  * number of premodifiers within NPs only
  * number of postmodifiers across all constituent types
  * number of postmodifiers within NPs only
  * branching index across all constituent types, i.e. the number of right-branching nodes minus number of left-branching nodes
  * branching index for NPs only
  * branching weight index: number of tokens covered by right-branching nodes minus number of tokens covered by left-branching nodes across all categories
  * branching weight index for NPs only 
  * modification index, i.e. the number of premodifiers minus the number of postmodifiers across all categories
  * modification index for NPs only
  * modification weight index: length in tokens of all premodifiers minus length in tokens of all postmodifiers across all categories
  * modification weight index for NPs only
  * coordination balance, i.e. the maximal length difference in coordinated constituents
  
  * density (density can be calculated using the ratio of folowing function words to content words) of determiners/quantifiers
  * density of pronouns
  * density of prepositions
  * density of punctuation marks, specifically commas and semicolons
  * density of auxiliary verbs
  * density of conjunctions
  * density of different pronoun types: Wh, 1st, 2nd, and 3rd person pronouns
  
  * maximal and average NP length
  * maximal and average AJP length
  * maximal and average PP length
  * maximal and average AVP length
  * sentence length

* Other features in your mind (ie., pre-defined patterns)

In [1]:
# Please write your code here
import requests
URL="http://www.values.com/inspirational-quotes"
response=requests.get(URL)
print(response.content)
#the source code of the page

b'<!DOCTYPE html>\n<html class="no-js" dir="ltr" lang="en-US">\n    <head>\n        <title>Inspirational Quotes - Motivational Quotes - Leadership Quotes | PassItOn.com</title>\n        <meta charset="utf-8">\n        <meta http-equiv="content-type" content="text/html; charset=utf-8" />\n        <meta http-equiv="X-UA-Compatible" content="IE=edge" />\n        <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1" />\n        <meta name="description" content="The Foundation for a Better Life | Pass It On.com">\n        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">\n        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">\n        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">\n        <link rel="manifest" href="/site.webmanifest">\n        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#c8102e">\n        <meta name="msapplication-TileColor" content="#c8102e">\n   

In [2]:
import requests 
from bs4 import BeautifulSoup 
  
URL = "http://www.values.com/inspirational-quotes"
r = requests.get(URL) 
  
soup = BeautifulSoup(r.content, 'html5lib') # If this line causes an error, run 'pip install html5lib' or install html5lib 
print(soup)

<!DOCTYPE html>
<html class="no-js" dir="ltr" lang="en-US"><head>
        <title>Inspirational Quotes - Motivational Quotes - Leadership Quotes | PassItOn.com</title>
        <meta charset="utf-8"/>
        <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
        <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
        <meta content="width=device-width,initial-scale=1.0,maximum-scale=1" name="viewport"/>
        <meta content="The Foundation for a Better Life | Pass It On.com" name="description"/>
        <link href="/apple-touch-icon.png" rel="apple-touch-icon" sizes="180x180"/>
        <link href="/favicon-32x32.png" rel="icon" sizes="32x32" type="image/png"/>
        <link href="/favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/>
        <link href="/site.webmanifest" rel="manifest"/>
        <link color="#c8102e" href="/safari-pinned-tab.svg" rel="mask-icon"/>
        <meta content="#c8102e" name="msapplication-TileColor"/>
        <meta conten

In [3]:
import requests
from bs4 import BeautifulSoup
import csv
URL = "http://www.values.com/inspirational-quotes"
r = requests.get(URL) 
   
soup = BeautifulSoup(r.content, 'html5lib') 
   
quotes=[]  # a list to store quotes 
   
table = soup.find('div', attrs = {'id':'all_quotes'})  
   
for row in table.findAll('div', 
                         attrs = {'class':'col-6 col-lg-3 text-center margin-30px-bottom sm-margin-30px-top'}): 
    quote = {} 
    quote['theme'] = row.h5.text 
    quote['url'] = row.a['href'] 
    quote['img'] = row.img['src'] 
    quote['lines'] = row.img['alt'].split(" #")[0] 
    quote['author'] = row.img['alt'].split(" #")[1] 
    quotes.append(quote) 
   
filename = 'inspirational_quotes.csv'
with open(filename, 'w', newline='') as f: 
    w = csv.DictWriter(f,['theme','url','img','lines','author']) 
    w.writeheader() 
    for quote in quotes: 
        w.writerow(quote)

In [4]:
import pandas as pd
csvfile=pd.read_csv('inspirational_quotes.csv')
print(csvfile)

          theme  ...                       author
0       EMPATHY  ...  <Author:0x00007f63d1fde468>
1       EMPATHY  ...  <Author:0x00007f63d2063c08>
2       EMPATHY  ...  <Author:0x00007f63d28edbd0>
3       EMPATHY  ...  <Author:0x00007f63d292f008>
4   GET OUTSIDE  ...  <Author:0x00007f63d2978730>
5   GET OUTSIDE  ...  <Author:0x00007f63d2b5e298>
6   GET OUTSIDE  ...  <Author:0x00007f63d2bad398>
7   GET OUTSIDE  ...  <Author:0x00007f63d2c019c0>
8   GET OUTSIDE  ...  <Author:0x00007f63d2c4ec98>
9   BEING THERE  ...  <Author:0x00007f63d2caf7c8>
10  BEING THERE  ...  <Author:0x00007f63d2ce8168>
11  BEING THERE  ...  <Author:0x00007f63d2d9a570>
12  BEING THERE  ...  <Author:0x00007f63d2dfbd98>
13  BEING THERE  ...  <Author:0x00007f63d2e1d308>
14       HEALTH  ...  <Author:0x00007f63d2e8b038>
15       HEALTH  ...  <Author:0x00007f63d2ecfdc8>
16       HEALTH  ...  <Author:0x00007f63d2f000e0>
17       HEALTH  ...  <Author:0x00007f63d2f68f78>
18       HEALTH  ...  <Author:0x00007f63d2fe65b8>


In [5]:
dat = pd.read_csv('inspirational_quotes.csv')
print(dat.shape)
dat.head(5)


(32, 5)


theme  ...                       author
0      EMPATHY  ...  <Author:0x00007f63d1fde468>
1      EMPATHY  ...  <Author:0x00007f63d2063c08>
2      EMPATHY  ...  <Author:0x00007f63d28edbd0>
3      EMPATHY  ...  <Author:0x00007f63d292f008>
4  GET OUTSIDE  ...  <Author:0x00007f63d2978730>

[5 rows x 5 columns]

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
# tokenize and build vocab
vectorizer.fit(dat)
# summarize
print(vectorizer.vocabulary_)
# encode document
vector = vectorizer.transform(dat)
# summarize encoded vector
print(vector.toarray())

{'theme': 3, 'url': 4, 'img': 1, 'lines': 2, 'author': 0}
[[0 0 0 1 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [1 0 0 0 0]]


In [7]:
from sklearn.feature_extraction.text import TfidfVectorizer

# create the transform
vectorizer = TfidfVectorizer()
# tokenize and build vocab
vectorizer.fit(dat)
# summarize
print(vectorizer.vocabulary_)
print(vectorizer.idf_)
# encode document
vector = vectorizer.transform(dat)
# summarize encoded vector

print(vector.toarray())

{'theme': 3, 'url': 4, 'img': 1, 'lines': 2, 'author': 0}
[2.09861229 2.09861229 2.09861229 2.09861229 2.09861229]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [8]:
from sklearn.feature_extraction.text import HashingVectorizer

vectorizer = HashingVectorizer(n_features=50)
# encode document
vector = vectorizer.transform(dat)
# summarize encoded vector
print(vector.shape)
print(vector.toarray())

(5, 50)
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  0.  0.  0

In [10]:
file = open("inspirational_quotes.csv")
reader = csv.reader(file)

In [11]:
data = [
    [(word.replace(",", "")
          .replace(".", "")
          .replace("(", "")
          .replace(")", ""))
    for word in row[2].lower().split()]
    for row in reader]

#Removes header
data = data[1:]

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer
v = TfidfVectorizer()
x = v.fit_transform(dat)#['author'])

In [13]:
x.toarray()

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [14]:
!pip install texthero

     |████████████████████████████████| 245kB 3.9MB/s 
     |████████████████████████████████| 1.4MB 12.3MB/s 
  Created wheel for nltk: filename=nltk-3.5-cp36-none-any.whl size=1434678 sha256=3720ad4303fa596f3f90e7f8a6fb0659c9837fa62954571b4edc6d4058caa14f
  Stored in directory: /root/.cache/pip/wheels/ae/8c/3f/b1fe0ba04555b08b57ab52ab7f86023639a526d8bc8d384306
Successfully built nltk
  Found existing installation: nltk 3.2.5
    Uninstalling nltk-3.2.5:
      Successfully uninstalled nltk-3.2.5


In [15]:
import texthero as hero
dat['tfidf'] = hero.tfidf(dat['author'])
dat['tfidf1'] = hero.tfidf(dat['lines'])

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [16]:
dat.head(35)

theme  ...                                             tfidf1
0       EMPATHY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
1       EMPATHY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.21100184...
2       EMPATHY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.19874988...
3       EMPATHY  ...  [0.0, 0.20459989540224074, 0.20459989540224074...
4   GET OUTSIDE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
5   GET OUTSIDE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2264375052034...
6   GET OUTSIDE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
7   GET OUTSIDE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
8   GET OUTSIDE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
9   BEING THERE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
10  BEING THERE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
11  BEING THERE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
12  BEING THERE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
13  BEING THERE  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
14       HEALTH  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
15       HEALTH  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
16       HEALTH  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
17       HEALTH  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.477...
18       HEALTH  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
19   CREATIVITY  ...  [0.0, 0.0, 0.0, 0.0, 0.23854663081799116, 0.0,...
20   CREATIVITY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.2856915388753275, ...
21   CREATIVITY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
22   CREATIVITY  ...  [0.0, 0.0, 0.0, 0.30238516732504916, 0.0, 0.0,...
23   CREATIVITY  ...  [0.0, 0.0, 0.0, 0.0, 0.3208342738683802, 0.0, ...
24     COURTESY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
25     COURTESY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
26     COURTESY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
27     COURTESY  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
28     COURTESY  ...  [0.3676454343871572, 0.0, 0.0, 0.0, 0.0, 0.0, ...
29     STRENGTH  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
30     STRENGTH  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
31     STRENGTH  ...  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

[32 rows x 7 columns]

In [17]:
tf1 = (dat['author'][0:31]).apply(lambda x: pd.value_counts(x.split(" "))).sum(axis = 0).reset_index()
tf1.columns = ['words','tf']
tf1

words   tf
0   <Author:0x00007f63d1fde468>  1.0
1   <Author:0x00007f63d2063c08>  1.0
2   <Author:0x00007f63d28edbd0>  1.0
3   <Author:0x00007f63d292f008>  1.0
4   <Author:0x00007f63d2978730>  1.0
5   <Author:0x00007f63d2b5e298>  1.0
6   <Author:0x00007f63d2bad398>  1.0
7   <Author:0x00007f63d2c019c0>  1.0
8   <Author:0x00007f63d2c4ec98>  1.0
9   <Author:0x00007f63d2caf7c8>  1.0
10  <Author:0x00007f63d2ce8168>  1.0
11  <Author:0x00007f63d2d9a570>  1.0
12  <Author:0x00007f63d2dfbd98>  1.0
13  <Author:0x00007f63d2e1d308>  1.0
14  <Author:0x00007f63d2e8b038>  1.0
15  <Author:0x00007f63d2ecfdc8>  1.0
16  <Author:0x00007f63d2f000e0>  1.0
17  <Author:0x00007f63d2f68f78>  1.0
18  <Author:0x00007f63d2fe65b8>  1.0
19  <Author:0x00007f63d304ba80>  1.0
20  <Author:0x00007f63d30c6870>  1.0
21  <Author:0x00007f63d312aed8>  1.0
22  <Author:0x00007f63d3193be0>  1.0
23  <Author:0x00007f63d32251f8>  1.0
24  <Author:0x00007f63d32b7008>  1.0
25  <Author:0x00007f63d333acc8>  1.0
26  <Author:0x00007f63d33ecc98>  1.0
27  <Author:0x00007f63d345d5d8>  1.0
28  <Author:0x00007f63d3507e98>  1.0
29  <Author:0x00007f63d35b4008>  1.0
30  <Author:0x00007f63d364ddc0>  1.0

In [18]:
import numpy as np
for i,word in enumerate(tf1['words']):
  tf1.loc[i, 'idf'] = np.log(dat.shape[0]/(len(dat[dat['author'].str.contains(word)])))

tf1

words   tf       idf
0   <Author:0x00007f63d1fde468>  1.0  3.465736
1   <Author:0x00007f63d2063c08>  1.0  3.465736
2   <Author:0x00007f63d28edbd0>  1.0  3.465736
3   <Author:0x00007f63d292f008>  1.0  3.465736
4   <Author:0x00007f63d2978730>  1.0  3.465736
5   <Author:0x00007f63d2b5e298>  1.0  3.465736
6   <Author:0x00007f63d2bad398>  1.0  3.465736
7   <Author:0x00007f63d2c019c0>  1.0  3.465736
8   <Author:0x00007f63d2c4ec98>  1.0  3.465736
9   <Author:0x00007f63d2caf7c8>  1.0  3.465736
10  <Author:0x00007f63d2ce8168>  1.0  3.465736
11  <Author:0x00007f63d2d9a570>  1.0  3.465736
12  <Author:0x00007f63d2dfbd98>  1.0  3.465736
13  <Author:0x00007f63d2e1d308>  1.0  3.465736
14  <Author:0x00007f63d2e8b038>  1.0  3.465736
15  <Author:0x00007f63d2ecfdc8>  1.0  3.465736
16  <Author:0x00007f63d2f000e0>  1.0  3.465736
17  <Author:0x00007f63d2f68f78>  1.0  3.465736
18  <Author:0x00007f63d2fe65b8>  1.0  3.465736
19  <Author:0x00007f63d304ba80>  1.0  3.465736
20  <Author:0x00007f63d30c6870>  1.0  3.465736
21  <Author:0x00007f63d312aed8>  1.0  3.465736
22  <Author:0x00007f63d3193be0>  1.0  3.465736
23  <Author:0x00007f63d32251f8>  1.0  3.465736
24  <Author:0x00007f63d32b7008>  1.0  3.465736
25  <Author:0x00007f63d333acc8>  1.0  3.465736
26  <Author:0x00007f63d33ecc98>  1.0  3.465736
27  <Author:0x00007f63d345d5d8>  1.0  3.465736
28  <Author:0x00007f63d3507e98>  1.0  3.465736
29  <Author:0x00007f63d35b4008>  1.0  3.465736
30  <Author:0x00007f63d364ddc0>  1.0  3.465736

In [19]:
import nltk
nltk.download('averaged_perceptron_tagger')
from nltk.tokenize import word_tokenize
nltk.download('punkt')
try1=[]
for i in dat['author']:
  text = word_tokenize(i)
  try1.append(nltk.pos_tag(text))

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [20]:
c_nn=0
c_vb=0

for i in try1:
  for j,k in i:
    
    if k=="NN":
      c_nn+=1
    if k=="JJ":
      c_vb+=1

In [21]:

c_nn

32

In [26]:
import spacy
nlp=spacy.load("en_core_web_sm")
for i in dat['author']:
  for token in nlp(i):
    print(token.text,"=>",token.pos_,"=>",token.tag_)

< => X => XX
Author:0x00007f63d1fde468 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d2063c08 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d28edbd0 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d292f008 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d2978730 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d2b5e298 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d2bad398 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d2c019c0 => ADJ => JJ
> => X => XX
< => X => XX
Author:0x00007f63d2c4ec98 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d2caf7c8 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d2ce8168 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d2d9a570 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d2dfbd98 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d2e1d308 => PROPN => NNP
> => X => XX
< => X => XX
Author:0x00007f63d2e8b038 => PROPN => 

In [23]:
import spacy
nlp=spacy.load("en_core_web_sm")
for i in dat['lines']:
  for token in nlp(i):
    print(token.text,"=>",token.pos_,"=>",token.tag_)

The => DET => DT
nature => NOUN => NN
of => ADP => IN
humanity => NOUN => NN
, => PUNCT => ,
its => DET => PRP$
essence => NOUN => NN
, => PUNCT => ,
is => AUX => VBZ
to => PART => TO
feel => VERB => VB
another => DET => DT
’s => PUNCT => ``
pain => NOUN => NN
as => SCONJ => IN
one => PRON => PRP
’s => PART => POS
own => ADJ => JJ
, => PUNCT => ,
and => CCONJ => CC
to => PART => TO
act => VERB => VB
to => PART => TO
take => VERB => VB
that => DET => DT
pain => NOUN => NN
away => ADV => RB
. => PUNCT => .
There => PRON => EX
is => AUX => VBZ
a => DET => DT
nobility => NOUN => NN
in => ADP => IN
compassion => NOUN => NN
, => PUNCT => ,
a => DET => DT
beauty => NOUN => NN
in => ADP => IN
empathy => NOUN => NN
, => PUNCT => ,
a => DET => DT
grace => NOUN => NN
in => ADP => IN
forgiveness => NOUN => NN
. => PUNCT => .
Empathy => NOUN => NN
is => AUX => VBZ
the => DET => DT
starting => NOUN => NN
point => NOUN => NN
for => ADP => IN
creating => VERB => VBG
a => DET => DT
community => NOUN =>